
### 查询
POST {{host}}/
Content-Type: application/json

{
  "username": "koobe"
}

### 添加
POST {{host}}/create
Content-Type: application/json

{
  "username": "koobe"
}

### 更新
POST {{host}}/update
Content-Type: application/json

{
  "username": "koobe"
}

### 单条查询
POST {{host}}/find
Content-Type: application/json

{
  "username": "koobe"
}

### 删除
POST {{host}}/delete
Content-Type: application/json

{
  "username": "koobe"
}